title: Budget Finds - AliExpress & Amazon Affiliates
de scription: Best budget deals with affiliate links
baseurl: "/budget-finds-blog"
url: "https://Deanthehandyman.github.io"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag