title: Budget Finds - AliExpress & Amazon Affiliates
de scription: Honest reviews and best budget deals with affiliate links using deansdeals0e-20
baseurl: "/budget-finds-blog"
url: "https://Deanthehandyman.github.io"

github_username: Deanthehandyman

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag